### ISSUE TITLE
System error if previously used Hero not found

### ISSUE THREAD

**Issue by Maxtream** [Warcraft-GO-Team/Warcraft-GO#12]
Initially when I tried to run server, there was a Debug Heroes added.
Predz Debug hero was set by default. BOTS took this Hero by default and started to leveling up with it.
When I remove debug.py file from /heroes folder and try to run the server. It will give me bunch of errors, that files are missing.
This is an issues that can be solved by cleaning up heroes table/users table from sqlite (sorry, didn't look how DB structure looks).
But I think there should be some check added, that when hero file does not exist, it should ignore those values from DB, to not cause any errors and might only display some warning message.

Situation like this can happen when for example you decided to disable hero temporarily, to debug it.

**Comment by Predz** [comment]
Thanks for reporting this. I will push a fix today, and I have a few updates that people will enjoy.

**Comment by Maxtream** [comment]
Thank you very much.
Can't wait for this meet_requirement functionality to hit the repo.

**Comment by Predz** [comment]
Fixed this with the new push: https://github.com/Warcraft-GO-Team/Warcraft-GO/commit/bed4ce6feba26e87ec55ccde2298ff63ecd31489

**Comment by Predz** [comment]
Enjoy the update :) 

https://github.com/Warcraft-GO-Team/Warcraft-GO/commit/e9580d6b2fca2a0cb7ef6dc1831da57fc49f6192

**Comment by Mahi** [comment]
I'm doing my mandatory military service for the next 6 to 9 months, and I'll only be available on weekends, so sorry for the late response from me.

Anyways, @Predz your solution should not really even affect the issue. In case the `active_hero_clsid` from the database is incorrect, the player's `hero` property remains `None` and gets set to a random starting hero [here](https://github.com/Warcraft-GO-Team/Warcraft-GO/blob/master/addons/source-python/plugins/wcgo/wcgo.py#L93-L95). And this process should be done outside of the database module anyways. I have *a lot* to do right now so I don't really have time to figure out the errors, but we should be able to find a better solution than this. What exactly are the errors you're receiving, @Maxtream?

**Comment by Mahi** [comment]
Sorry for the late response from me, I'm doing my mandatory military service for the next 6 to 9 months, so I'll only be available on weekends.

Anyways, @Predz your solution should not really even affect the issue. In case the `active_hero_clsid` from the database is incorrect, the player's `hero` property remains `None` and gets set to a random starting hero [here](https://github.com/Warcraft-GO-Team/Warcraft-GO/blob/master/addons/source-python/plugins/wcgo/wcgo.py#L93-L95). Even if this is a proper soluton, it should be done outside of the database module. [I've reverted the change for now.](https://github.com/Warcraft-GO-Team/Warcraft-GO/commit/8fcaaca0556340125699b983578da6221c544a28)

I have *a lot* to do right now so I really don't have time to figure out the errors (maybe tomorrow...), but we should be able to find a better solution than this. What exactly are the errors you're receiving, @Maxtream?

**Comment by Mahi** [comment]
Based on @Maxtream's comment [here](https://github.com/Warcraft-GO-Team/Warcraft-GO/issues/13#issuecomment-172148483), this is not a bug, but intended behaviour. Inside of `wcgo/configs.py` file, we have [this](https://github.com/Warcraft-GO-Team/Warcraft-GO/blob/8fcaaca0556340125699b983578da6221c544a28/addons/source-python/plugins/wcgo/configs.py#L136) line which contains the starting heroes (the heroes that are given to each player for free). You need to change the starting heroes to match the new heroes, since you no longer have `Predz_Debug_Hero` on your server.

**Comment by Predz** [comment]
NIcely caught Mahi. I didn't notice this until you had pointed it out. Have been at work all day so hadn't really had time to check his errors.
