### ISSUE TITLE
Can't start plugin after latest changes

### ISSUE THREAD

**Issue by Maxtream** [Warcraft-GO-Team/Warcraft-GO#13]
After commits
1a307fc5afe94036e5ef19a6eff35576872d395d
bed4ce6feba26e87ec55ccde2298ff63ecd31489
e9580d6b2fca2a0cb7ef6dc1831da57fc49f6192

Plugin does not want to start. Receive strange error that can not really debug. Not enough knowledge with python yet.

Tried to manually add changes from only from this commit e9580d6b2fca2a0cb7ef6dc1831da57fc49f6192 (most I'm interested in right now).
It did started, but hero requirements didn't worked. It was displayed, but Hero was still purchasable. Did anyone tested it?

**Comment by Predz** [comment]
Yeh I am testing it atm, had a few issues due to a lot of changes in the core of Source Python. I am working on them at the moment ;)

**Comment by Predz** [comment]
As long as you have the most recent build of SP, the newest commits should make it work. If you get any errors please copy them here so I can take a look. :)

**Comment by Maxtream** [comment]
folder: steamcmd/cs_go/csgo
1)
wget http://build.affecta.net/job/Source.Python/lastSuccessfulBuild/artifact/release/source-python-csgo-January-15-2016.zip
unzip source-python-csgo-January-15-2016.zip
2)
https://github.com/Mahi/EasyPlayer/releases/download/1.3/EasyPlayer-1.3.zip
unzip EasyPlayer-1.3.zip
3)
git init
git remote add origin https://github.com/Warcraft-GO-Team/Warcraft-GO.git
git fetch
git checkout -t origin/master

Then after running the server:
sp load wcgo

[SP] Loading plugin 'wcgo'... 
 
[SP] Caught an Exception: 
Traceback (most recent call last): 
  File '../addons/source-python/packages/source-python/plugins/manager.py', line 71, in __missing__ 
    instance = self.instance(plugin_name, self.base_import) 
  File '../addons/source-python/packages/source-python/plugins/instance.py', line 82, in __init__ 
    self._plugin = import_module(import_name) 
  File '../addons/source-python/plugins/wcgo/wcgo.py', line 30, in <module> 
    import wcgo.menus 
  File '../addons/source-python/plugins/wcgo/menus/__init__.py', line 4, in <module> 
    from wcgo.menus.main import main_menu 
  File '../addons/source-python/plugins/wcgo/menus/main.py', line 10, in <module> 
    import wcgo.player 
  File '../addons/source-python/plugins/wcgo/player.py', line 10, in <module> 
    import easyplayer 
  File '../addons/source-python/packages/custom/easyplayer/__init__.py', line 3, in <module> 
    from easyplayer.effect import PlayerEffect 
  File '../addons/source-python/packages/custom/easyplayer/effect.py', line 4, in <module> 
    from listeners.tick import tick_delays 
 
ImportError: cannot import name 'tick_delays' 
 
 
[SP] Plugin 'wcgo' was unable to be loaded.

**Comment by Predz** [comment]
Oh sorry, this isn't actually a WCGO problem. You need to update your EasyPlayer too. Currently Mahi isn't around to accept my pull request for EasyPlayer, so you will need to use my version of it.

https://github.com/Predz/EasyPlayer

**Comment by Maxtream** [comment]
Ok, yes. With this it worked.

But now again, removing hero will cause server to error for whatever reason
[SP] Caught an Exception: 
Traceback (most recent call last): 
  File '../addons/source-python/packages/source-python/plugins/manager.py', line 77, in __missing__ 
    instance.globals['load']() 
  File '../addons/source-python/plugins/wcgo/wcgo.py', line 64, in load 
    'Invalid starting hero clsid: '{0}''.format(clsid)) 
 
ValueError: Invalid starting hero clsid: 'Predz_Debug_Hero' 


And requirements for hero ignored :)

**Comment by Mahi** [comment]
I have now merged @Predz's pull request so this issue is done. What comes to your error, @Maxtream, the discussion should be continued in the [original issue](https://github.com/Warcraft-GO-Team/Warcraft-GO/issues/12).
