### ISSUE TITLE
Cant run WCGO

### ISSUE THREAD

**Issue by solkii** [Warcraft-GO-Team/Warcraft-GO#25]
I've got troubles loading the wcgo plugin.

[SP] Loading plugin 'wcgo'... 

[SP] Caught an Exception: 
Traceback (most recent call last): 
File '../addons/source-python/packages/source-python/plugins/manager.py', line 71, in __missing__ 
instance = self.instance(plugin_name, self.base_import) 
File '../addons/source-python/packages/source-python/plugins/instance.py', line 82, in __init__ 
self._plugin = import_module(import_name) 
File '../addons/source-python/plugins/wcgo/wcgo.py', line 30, in 
import wcgo.menus 
File '../addons/source-python/plugins/wcgo/menus/__init__.py', line 4, in 
from wcgo.menus.main import main_menu 
File '../addons/source-python/plugins/wcgo/menus/main.py', line 10, in 
import wcgo.player 
File '../addons/source-python/plugins/wcgo/player.py', line 10, in 
import easyplayer 

ImportError: No module named 'easyplayer' 

[SP] Plugin 'wcgo' was unable to be loaded. 

Thats everything i could figure out till now.
I am pretty new to python so maybe it is very obvious.

Hoping to hear from you

solki

**Comment by satoon101** [comment]
WC:GO requires the custom package [EasyPlayer](https://github.com/Mahi/EasyPlayer) be installed on the server.
