### ISSUE TITLE
Configuration in Python files?

### ISSUE THREAD

**Issue by satoon101** [Warcraft-GO-Team/Warcraft-GO#3]
Most people who will use this plugin are not going to be programmers.  They aren't really going to fare well trying to change configurations the way you currently have it setup.  I would suggest creating a .cfg file with [ConfigManager](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/config/manager.py#L49) or an .ini file with ConfigObj, as these are much easier to understand and are fairly standard already in Source-engine configurations.

The biggest advantage of using  [ConfigManager](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/config/manager.py#L49) is that all configuration values are then assigned to a ConVar.  This allows server operators/admins to change those values on the fly and even able to use map-based values.

**Comment by Mahi** [comment]
Very solid point, I do agree with you that we should use `.ini` or `.cfg` instead of Python files. I will look into this later tonight.

> The biggest advantage of using [ConfigManager](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/config/manager.py#L49) is that all configuration values are then assigned to a ConVar. This allows server operators/admins to change those values on the fly and even able to use map-based values.

That's new to me, sounds good! Thanks for the suggestion.

**Comment by satoon101** [comment]
If you want, I can make another pull request with some of the changes.  I didn't want to do that before knowing that this was a change you wanted to make.

**Comment by Mahi** [comment]
That would be more than awesome. I wasn't aware myself that this was a change I wanted to make, but your points were solid and I see absolutely no (meaningful) downside of changing the Python file to a better config format.

**Comment by Mahi** [comment]
Fixed in @satoon101's PR: https://github.com/Warcraft-GO-Team/Warcraft-GO/commit/be8e0fcbd055ed729bfd0318a67e2959a1ff9d60

**Comment by satoon101** [comment]
Unfortunately, I have run out of time to work on this today.  I have a portion of it done, though.  I will finish it when I get the opportunity.

**Comment by Mahi** [comment]
Yeah I accidentally closed it, my bad. We'll wait even if it takes two weeks to finish, not in a hurry! :) But let us know asap if you can't find time to implement it and we will.

**Comment by satoon101** [comment]
I am almost done with this, but I do have one issue.  I was going to include a list of possible heroes for the starting_heroes cvar, and possibly also a list of categories for default_hero/item_category, but the fact that the configuration is used in the construction of those classes prevents me from doing so.  For now, I will just implement it without, but I would suggest trying to find a way, at some point, to allow for these enhancements to the cfg file.

**Comment by Mahi** [comment]
Once more @satoon101, thank you very much!
